# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "SocialX"
client_id = "3c66fdcb5846b9087ce9b6293b78de41"
application_url = "https://7128-49-34-140-83.ngrok-free.app/SocialX"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "app-tester-001.myshopify.com"
